### ISSUE TITLE
Server Crash with Wizardry

### ISSUE THREAD

**Issue by andrewan719** [CleanroomMC/LibrarianLib#4]
While using Cleanroom Loader, my game crashed when dropping a book into a Wizardry Mod mana pool, and it seems to be linked to LibrarianLib.

After testing with just Wizardry mod, LibrarianLib-continuous, and Forgelin-continuous (as well as required dependencies for Cleanroom Loader), this issue still persists. It also persists between an instance with Cleanroom installed as well as a traditional Forge instance.

Log:
https://mclo.gs/dpiCutz

**Comment by ChAoSUnItY** [comment]
Fixed in 4.22-2.0-2.
